dist: trusty
sudo: required
language: go
go:
- 1.9.x
go_import_path: github.com/terraform-providers/terraform-provider-cf
install:
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
- go get gopkg.in/alecthomas/gometalinter.v2
- gometalinter.v2 --install
script:
- travis_wait 360 scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: FV+O96XUOzliHe1V5ycA6WG1UhZe2UOMWtwlct5X+iHezw/EETyAhVzi/s5Zzs3Nj409k48tF3glRFa8LlgI1NRWMOCRU0Uu/RPySBUJvun74sX1siCMTZdYKUSC0RwlgDCOHrB0LGpeuP0XDB/PTUzYweEnxlBS2rk8X1gEgOgw7GIUzGtQBNROQ6xTfUcFUovDWLmOEHegfCb5ZjpYPi2BOIHg9xju/VvmJTflFSMP210QE+SBWpA+P4lHiwXXkaDqQRnDMHVFYFA8ul2jucrTNhMuKPM/rsKyGF2+HMUWu0g3zzGJI8W3Zp8RoVa+eS4DywbtiLvthG/mNh9o8a0HINgyTQfoO7dZega2WNDO4eT+VsgQohn60gTWIk3JJhyAWPPy8nUuY3MWTOgLQicQjInUqvcpV+8BvpBjFjFVkJ+TrL8eJSWbvyGuoqC1dINRJNjZ6343IXIcw4lMMt8fJbwJ8OJCd2av1JMcw8JZPTXjy76H/ENiPwTVegifxZ4h8VeVyG88IHDMZsseqY33cFeYF3T2qkHzbkl2oWD8IgXuCsR4HEw7kffjEp5cS/qdDNGC5IeBfDObrMfcYGu9kX5QlSirBrD/ld0dcQ8t4Y3FhJN+xt5IWp6anqUaCpYwNVA6rGQ9ItozrVFkuGy5t735O/sv6rB05IgBbqQ=
  file:
  - bin/terraform-provider-cf_windows_amd64.exe
  - bin/terraform-provider-cf_linux_amd64
  - bin/terraform-provider-cf_darwin_amd64
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: mevansam/terraform-provider-cf
env:
  global:
    - secure: MK9IFpUVsb4GHAgL3ird6U5G5w+XAXgam3e3Iq0Bd5eN1a4I846gmkeM8MbRoGSmEeac0zNen7UMdlo+/LQnGlM9x/27BqKseHL89bpI5d1vZT/4aL7ZDbUs/KNXGEXbGHvxJPY8w/NAKDWbE9H/5B4VuKdpqRJM0hLvqQfcVG2EJM2OWINqPEIt5TiNKmBTM+PC48VTAFYyiclcS6t+XaJHqF8Bre0ufcvZ9scH81WaFD8KEziV1szE8YpebcMt3PSPtsyfaPvn/Fa3U4zpVfoSn6/ArukxL/004zSFjUFqgAiIkItWKhnV25/0HTahAelhb/1ychLBVJIwx3TZR4fQ/GgHVnvmFzfo2lEDKLi0aVxbfO034IBX7DViXdoYlGBnh0QmH6JxTMCqwOe2JtLImB9VQbZ0DZl+/fTPv0vLmlwpdMoPcLh17oo63Rlg0RIGNQfEoA283IC1jaXL2x83frjgp0RI1vWu+o9TYe/8CivB1Cp/MrAu286xQsyWAJKjgh5PzF5PPdjhoOfKo1a7r1sXnozClfeAzjTkOU08yE7u72FP47wjHylRstHsv16YmrIw2NFsvIlDdNW5p0D2TdL4LfW15knRFK5Q6ftqh97AUPI9Qp5cb9crIQ9eWC396P6DntbIYPcjpY5gQXRsYugpHvOz3Gz7NIYFLbg=
    - secure: aK6tAaGKElXoBEaLMZ6Pn0TNUR2XiUeE6//MsFpUf8Uq4GBQ08JyUGm0b3uORpDIWGa27kXNMfpa9j15i9WBG/6cO18OAWIQa4xuhm6zyh7oHv4U1RlMZBKBOV9ode1y+JqQ2MQ9bzpNhdw49JlsmGpYfhATNywidV7JssVA74gLL7fw5A3xX8vDfsyzPXpyjz+9SIsj4Go2mw9RQpKw43EdRv9+rVk45yEFCCKzMA8bIqnxRjrbjOUDqNjCAK1K6TCddtm3wRyDOeIVugiigfbqAF+t8DiivxVZgLMQIEnDjCHF50GUpF66rp23rl6N32MB49hwkGyTVYGAjVeBBbIb+fVfH4S+f7F3I9dU/GqATJpfvxnd19gyzoj3fBQrC4GrtPagzZWU36HSsp2/r2wwHYoWY12VvgzeTdmXBJQCR80fXax4lGvcOg/NLYC0XoDvkwTEuJ40KQHeuA9gIWlI/YyZBQT68svCqelrBsJVl8SH00aDZGmxedTzpKjaggBGdUEsFOeiCZ3CrbSDq1G8aiuNO5RUMXa7SvD84dDlhXV0yZWQhgJ5jpKNsaE55o/AJlsDmPh7QhtGRLy0iPPLcg7DX9/ZCVJPko1TsQ05nsgOVr8IeedHn/3yQQnKVz2/5Az/SLjZbxzIJ1xOgW20Ate5MZ8qRGik6MB5iZU=
    - secure: "Wi3umxHj4ifEkUXvY6jElwVEHultQsKIAoqnCXYWdTSoDWWZRVcZctAYvhiRNKUBLNfmExV4qdvTqDQtmb36XNMv8OwXSh25gSaf2mxa4NrdxKDhWQuZokvtwAbjSY+7gHo9TiVmm0ewNA6TFHWojLVLY4d26i1xKKN8AFnbRXooUHnjLae72ZL3EOnkoc6FECVjk5nTT95dMTPDxUJGBQ2xxMO7uNZYX+gVH++p7umCBMsyfW/CPd2YqLUB3e/kjzEM9A++C4WisrZRFZbTLp/k4n9AxZiGyZQYjlI7Xx7F/ahuKmXmVhq9z0Ai5dmTrL6iIZIbEXIAK2MVHDBG97MAau4kEdShCcBpFfaIBHOp13M9XWvS0CD3GZ8au+U2b/xsDJ+hOYfGMNicqzMuQ+hmQWen8FDiLc25NHfqT8kJPtQYzIMwUjl+U3kN+WZC0XfUOCxkR7hin/ozSqlP1/rfCe3lov/zcpc2ZopPAwczXtWFb3eM3pHNLCKzNwPg+yYXbcNNpfHfkFQVbS+viEduvslOWDFvtvGUcSpiX4lqETX2ScfmaKeh1miOWaf+5jGCke07wkf/JElEP3SAjK/ul+Z6/CnCxHiGS19wcKM006iBtptU0egfSm5nT1DzlEYhU9Kc0LMPMXcpOrFNORJBowtM3kPesfq49yR2DlE="
